name: generate-and-deploy-html

on:
  push:
    paths:
      - "index.md"
      - "index_ptbr.md"  # ✅Translated PT-BR
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install modern Pandoc (3.x)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Generate HTML with Pandoc (modern)
        run: |
          pandoc index.md \
            --standalone \
            --metadata pagetitle="nohello" \
            --css "assets/css/pandoc.css" \
            --from markdown \
            --to html5 \
            --output index.html

      - name: Generate HTML Portuguese Brazilian with Pandoc (modern)  # ✅ Adicione este passo
        run: |
          pandoc index_ptbr.md \
            --standalone \
            --metadata pagetitle="nohello - Português" \
            --css "assets/css/pandoc.css" \
            --from markdown \
            --to html5 \
            --output index_ptbr.html

      - name: Minify HTML
        uses: docker://tdewolff/minify
        with:
          args: -o index.html index.html

      - name: Minify HTML Portuguese Brazilian  # ✅ Adicione este passo
        uses: docker://tdewolff/minify
        with:
          args: -o index_ptbr.html index_ptbr.html

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
